mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace = 'polls')),
    url(r'^rango/', include('rango.urls', namespace = 'rango')),

)
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('', 
	url(r'^$', views.index, name='index'),
	url(r'^about/$', views.about, name='about')
)

rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('', 
	url(r'^$', views.index, name='index'),
	url(r'^about/$', views.about, name='about'),
	url(r'^category/(?P<category_name_url>\w+)/$', views.category, name='category'),
	url(r'^add_category/$', views.add_category, name='add_category'),
	url(r'^category/(?P<category_name_url>\w+)/add_page/$', views.add_page, name='add_page'),
	url(r'^register/$', views.register, name='register'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
)

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.
class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):  # Python 3: def __str__(self):
		return self.question

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	poll = models.ForeignKey(Poll)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __unicode__(self):
		return self.choice_text

rango/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length = 128, unique = True)

	def __unicode__(self):
		return self.name

class Page(models.Model):
	category = models.ForeignKey(Category)
	title = models.CharField(max_length = 128)
	url = models.URLField()
	views = models.IntegerField(default = 0)

	def __unicode__(self):
		return self.title

class PageAdmin(admin.ModelAdmin):
	list_display = ('title', 'category', 'url', 'views')

class UserProfile(models.Model):
	user = models.OneToOneField(User)

	website = models.URLField(blank = True)
	picture = models.ImageField(upload_to = 'images/profile_images', blank = True)

	def __unicode__(self):
		return self.user.username

polls/views.py
from django.http import HttpResponse

# Create your views here.
def index(request):
	return HttpResponse("Polls says hello world!<br><a href='/rango/about'>Go to about page</a>")

def about(request):
	return HttpResponse("ABOUT POLLS")

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from rango.models import Category, Page
from rango.form import CategoryForm, PageForm, UserForm, UserProfileForm

# Create your views here.
def index(request):
	category_list = Category.objects.order_by('-name')[:5]
	context_dict = {'categories': category_list}
	for category in category_list:
		category.url = category.name.replace(' ', '_')

	return render(request, 'rango/index.html', context_dict)

def about(request):
	return HttpResponse("About page")

def category(request, category_name_url):
	category_name = category_name_url.replace('_', ' ')
	context_dict = {'category_name' : category_name, 'category_name_url' : category_name_url}

	try:
		category = Category.objects.get(name = category_name)

		pages = Page.objects.filter(category = category)

		context_dict['pages'] = pages
		context_dict['category'] = category
	except Category.DoesNotExist:
		pass
	return render(request, 'rango/category.html', context_dict)

def add_category(request):
	#context = RequestContext(request)

	if request.method == 'POST':
		form = CategoryForm(request.POST)

		if form.is_valid():
			form.save(commit = True)
			return index(request)
		else:
			print form.errors
	else:
		form = CategoryForm()

	return render(request, 'rango/add_category.html', {'form' : form})

def add_page(request, category_name_url):
	#context = RequestContext(request)
	category_name = category_name_url.replace('_', ' ')

	if request.method == 'POST':
		form = PageForm(request.POST)

		if form.is_valid():
			page = form.save(commit = False)

			try:
				cat = Category.objects.get(name = category_name)
				page.category = cat
			except Category.DoesNotExist:
				return render(request, 'rango/add_category.html')

			page.views = 0
			page.save()

			return category(request, category_name_url)
		else:
			print form.errors
	else:
		form = PageForm()

	return render(request, 'rango/add_page.html', {'category_name_url': category_name_url,
             'category_name': category_name, 'form': form})

def register(request):
	registered = False

	if request.method == 'POST':
		user_form = UserForm(data = request.POST)
		profile_form = UserProfileForm(data = request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit = False)
			profile.user = user

			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
			profile.save()

			registered = True
		else:
			print user_form.errors, profile_form.errors
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()
	return render(request, 'rango/register.html', {'user_form' : user_form, 'profile_form' : profile_form, 'registered' : registered})

def user_login(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username = username, password = password)

		if user:
			if user.is_active:
				login(request, user)
				#return render(request, 'rango/index.html', {'username' : user.username})
				return HttpResponseRedirect('/rango/')
			else:
				return HttpResponse("Your Rango account is disabled.")
		else:
			print "Invalid login details: {0}, {1}".format(username, password)
	else:
		return render(request, 'rango/login.html', {})

def user_logout(request):
	logout(request)
	return HttpResponseRedirect('/rango/')

templates/rango/add_category.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>
        <h1>Add a Category</h1>

        <form id="category_form" method="post" action="{% url 'rango:add_category' %}">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Create Category" />
        </form>
    </body>

</html>

templates/rango/add_page.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>
        <h1>Add a Page</h1>

        <form id="category_form" method="post" action="{% url 'rango:add_page' category_name_url %}">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Create Page" />
        </form>
    </body>

</html>

templates/rango/category.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>
        <h1>{{ category_name }}</h1>
        {% if category %}
            {% if pages %}
            <ul>
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>No pages currently in category.</strong>
            {% endif %}
        {% else %}
            The specified category {{ category_name }} does not exist!
        {% endif %}

        <a href="/rango/category/{{category_name_url}}/add_page/">Add new page</a>
    </body>
</html>

templates/rango/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>

        <h1>Rango says..hello world!</h1>
        {% if user.is_authenticated %}
            <h2>Hello, {{user}}</h2> <a href="/rango/logout/">Logout</a>
        {% endif %}

        {% if categories %}
            <ul>
                {% for category in categories %}
                <!-- Following line changed to add an HTML hyperlink -->
                <li><a href="/rango/category/{{ category.url }}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
       {% else %}
            <strong>There are no categories present.</strong>
       {% endif %}
<a href="/rango/add_category/">Add a New Category</a>
<br>
<a href="/rango/register/">Register Here</a>
<a href="/rango/login/">Login</a>

    </body>
</html>

templates/rango/login.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Is anyone getting tired of repeatedly entering the header over and over?? -->
        <title>Rango</title>
    </head>

    <body>
        <h1>Login to Rango</h1>

        <form id="login_form" method="post" action="/rango/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>

    </body>
</html>

templates/rango/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>
        <h1>Register with Rango</h1>

        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="/rango/">Return to the homepage.</a><br />
        {% else %}
        Rango says: <strong>register here!</strong><br />

        <form id="user_form" method="post" action="/rango/register/"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
    </body>
</html>